### PR TITLE
Adapt for tripleo heat templates workflow

### PR DESCRIPTION
**Pull request by bogdando**
* Adapt for docker_steps.j2 et al (t-h-t ocata|pike)
* Relax HOT/CFN version requirements
* Add filter for nodes' names
* Allows to depict filtered graphs focused on
  particular things like deployment steps
* Add colored decors and more docs
* Document requirements, a kind of

Signed-off-by: Bogdan Dobrelya <bogdando@mail.ru>

### CODE REVIEW

**Comment by bogdando** [comment]
note, this is a kind of works with t-h-t for Pike, for me. Although there are many omitted nodes not included in the graph. Perhaps it should be improved with parsing multiple depends_on with jinja2 sauce? But at least it depicts something...

@larsks @hardys JFYI ^^

**Comment by elzibubble** [comment]
I have no interest in maintaining this going forward I'm afraid.

**Comment by bogdando** [comment]
@lxsli no problem, I'll keep it with my fork then. Thank you for a great tool! I was impressed it keeps working w/o problems after the 3 years passed for OpenStack and specifically Heat.

**Comment by elzibubble** [comment]
Thanks for the kind words :)

**Pull request closed without merging**
